[package]
name = "sql-layer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlparser = { version = "0.39.0", features = ["serde", "bigdecimal"] }
thiserror = "1.0"
serde = { version = "1", features = ["derive","rc"] }
bigdecimal = { version = "0.4.1", features = ["serde", "string-only"] }
futures = "0.3"
ordered-float = "4.2.0"
